### ISSUE TITLE
Cross distribution Linux package

### ISSUE THREAD

**Issue by dreaddr** [sentinel-official/desktop-client#20]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that a universal Linux package is not supported

**Describe the solution you'd like**
Cross distribution Linux package please, don't limit this to just .deb, perhaps a .flatpak or .appimage is best.

**Describe alternatives you've considered**
Obviously the only other option is to compile with the source and maintain it by myself, which is not pleasant.

**Additional context**
Limiting to just .deb doesn't allow many options to installation unfortunately.

**Comment by v1rtl** [comment]
Latest release has an AppImage so i think this could be closed

**Comment by bsrinivas8687** [comment]
Thank you @talentlessguy
